version: "3.8"
services:
  flask-app:
    build: './flask-app'
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery_worker
      - mongodb
    environment:
      - FLASK_ENV=development

  celery_worker:
    build:
      context: ./flask-app
    entrypoint: celery
    command: -A tasks worker -B --loglevel=info
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - '6379:6379'
    hostname: redis

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    hostname: mongodb
